DOMAIN = "https://www.alltime.ru"
HTML_ENCODING = 'windows-1251'
RETRY_AFTER = 0.5  # sec

CATALOG_PAGE = DOMAIN + "/watch/man/"
CATALOG_PAGES = 150
ITEMS_PER_PAGE = 100

CATALOG_PARALLEL_CONNECTIONS = 10
CATALOG_PARSE_QUEUE = 30
PAGES_PARALLEL_CONNECTIONS = 50
PAGES_PARSE_QUEUE = 20
