DOMAIN = "https://www.alltime.ru"
HTML_ENCODING = 'windows-1251'
PARALLEL_CONNECTIONS = 10  # per process
RETRY_AFTER = 0.5  # sec

CATALOG_PAGE = DOMAIN + "/watch/man/"
CATALOG_PAGES = 150
ITEMS_PER_PAGE = 100

CATALOG_QUEUE = 5
PAGES_QUEUE = 20
