# Generated by Django 2.2.4 on 2019-09-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogWatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Модель')),
                ('href', models.URLField(max_length=1024, verbose_name='Ссылка')),
                ('image_href', models.URLField(max_length=1024, verbose_name='Рис.')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('price_old', models.PositiveIntegerField(null=True, verbose_name='Цена 2')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Модель в каталоге',
                'verbose_name_plural': 'Модели в каталоге',
            },
        ),
    ]
