# Generated by Django 2.2.5 on 2019-09-07 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alltime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_type', models.CharField(max_length=100, null=True, verbose_name='Тип механизма')),
                ('case', models.CharField(max_length=100, null=True, verbose_name='Корпус')),
                ('face', models.CharField(max_length=100, null=True, verbose_name='Циферблат')),
                ('bracelet', models.CharField(max_length=100, null=True, verbose_name='Браслет')),
                ('water', models.CharField(max_length=100, null=True, verbose_name='Водозащита')),
                ('light', models.CharField(max_length=100, null=True, verbose_name='Подсветка')),
                ('glass', models.CharField(max_length=100, null=True, verbose_name='Стекло')),
                ('calendar', models.CharField(max_length=100, null=True, verbose_name='Календарь')),
                ('signal', models.CharField(max_length=100, null=True, verbose_name='Сигнал')),
                ('size_raw', models.CharField(max_length=100, null=True, verbose_name='Размеры*')),
                ('country', models.CharField(max_length=100, null=True, verbose_name='Страна')),
                ('text', models.TextField(verbose_name='Текст')),
                ('catalog_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alltime.CatalogWatch', verbose_name='Страница в каталоге')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
    ]
